### PR TITLE
Enable capturing of test stdout on testall

### PR DESCRIPTION
**Pull request by jnfingerle**
Fixes https://github.com/kategengler/ember-try/issues/30

### CODE REVIEW

**Comment by rwjblue** [comment]
I think in general, it would be better to configure `testem.json` to use a different reporter (that would make it much less prone when parsing stdout).

See https://github.com/poteto/ember-cli-flash/commit/5df7f87ab888bbebb5db6c6ff9954e7271b65a54 for an example of using `testem` output `xunit` format from test runs (IMHO this is much better than using stdout).

**Comment by jnfingerle** [comment]
I'm using .tap reports that are a bit more robust for this use case. Anyway, testem doesn't have a concept of different runs with different configurations. Therefore ember-try would have to overwrite testem's report_file configuration option or provide a hook to have this file copied to another destination after each run.

**Comment by rwjblue** [comment]
ember-try already modified the bower.json for each run, this could be a very similar thing. I definitely think we should avoid using stdout from 'ember test' runs, we have had MANY issues reported in ember-cli due to addons modifying the console output (stray console.logs and whatnot).

**Comment by jnfingerle** [comment]
Ok, if we go this path, what should the ember-try.json file look like? Like this ...

```js
module.exports = {
  scenarios: [
    {
      name: 'Ember 1.10 with ember-data',
      dependencies: {
        'ember': '1.10.0',
        'ember-data': '1.0.0-beta.15'
      },
      testem: { /* to be merged into the existing testem.json */
        "report_file": "path/to/some/file.tap",
      }
    },
    { /*...*/ }
  ]
};
```

Or do you think of something more generic?

**Comment by jnfingerle** [comment]
Ok, here's a version that changes testem.json: https://github.com/kategengler/ember-try/pull/32

**Comment by mike-north** [comment]
I wonder if some more generic hooks for things like `afterScenarioSetup` and `beforeScenarioTeardown` would work for this?

**Comment by jnfingerle** [comment]
For me anything that does the job is ok.

**Pull request closed without merging**
